# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

sudo: required

julia:
  - 0.6
  - nightly

notifications:
  email:
      recipients:
          - andersd@riseup.net
      on_success: never # default: change
      on_failure: always # default: always

matrix:
  allow_failures:
    - julia: nightly

before_script:
  - julia -e 'info("Preparing Python"); ENV["PYTHON"]=""; Pkg.add("PyCall"); Pkg.build("PyCall")'

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Granular"); ENV["PYTHON"]=""; Pkg.build("PyCall"); Pkg.build("PyPlot"); Pkg.test("Granular"; coverage=true)';

deploy:
  - provider: script
    script: julia -e 'cd(Pkg.dir("Granular")); Pkg.add("Coverage"); Pkg.add("Documenter"); using Coverage; Codecov.submit(Codecov.process_folder()); cd(Pkg.dir("Granular")); include(joinpath("docs", "make.jl"))'
    on:
      os: linux
