# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - release
  - nightly
notifications:
  email:
      recipients:
          - andersd@riseup.net
      on_success: never # default: change
      on_failure: always # default: always
deploy:
  - provider: script
    script: julia -e 'cd(Pkg.dir("SeaIce")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
    on:
      os: linux
