# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email:
      recipients:
          - andersd@riseup.net
      on_success: never # default: change
      on_failure: always # default: always
script:
# push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("SeaIce")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
