# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

julia:
  - 0.6
  - 0.7
  - nightly

notifications:
  email:
      on_success: never # default: change
      on_failure: always # default: always

addons:
  apt:
    packages:
    - gnuplot
    - imagemagick

before_script:  # NetCDF is not required, but test its dependent functions anyway
  - julia -e 'VERSION <= v"0.6.99" && Pkg.add("NetCDF")'

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Granular"); Pkg.test("Granular"; coverage=true)';

deploy:
  - provider: script
    script: julia -e 'cd(Pkg.dir("Granular")); Pkg.add("Coverage"); Pkg.add("Documenter"); using Coverage; Codecov.submit(Codecov.process_folder()); cd(Pkg.dir("Granular")); include(joinpath("docs", "make.jl"))'
    on:
      os: linux
      julia: 0.6

matrix:
  allow_failures:
  - julia: nightly
